### ISSUE TITLE
layoutSubviewsでの各subviewのサイズの求め方

### ISSUE THREAD

**Issue by matsumoto777** [Waqas-Hirose/CustomViewPractice#1]
これをよく見てほしいです。
https://github.com/YuukiHirama/Task2

layoutSubviews内で各viewのサイズを求めるのにsizeThatFitsを用いてます。
https://developer.apple.com/documentation/uikit/uiview/1622625-sizethatfits

*frameやboundsはlayoutSubviewsの結果としてセットされるものです。

**Comment by Waqas-Hirose** [comment]
I have used "sizeThatFits()" in "layoutSubviews"
