### ISSUE TITLE
"Log in"ボタンとAutoLogin Switchとの隙間が大きい

### ISSUE THREAD

**Issue by matsumoto777** [Waqas-Hirose/CustomViewPractice#6]
AutoLogin Switchとの隙間について。
"Log out"ボタンは正しい。
"Log in"ボタンは大きい

![スクリーンショット 2019-11-27 15 51 47](https://user-images.githubusercontent.com/28752302/69700532-05b2e780-112e-11ea-9f2b-885665133cd4.png)

Hirama-sanのソースと比べて何が異なるか研究してほしいです。
https://github.com/YuukiHirama/Task2/blob/master/Task2/Task2/CustomView.swift

**Comment by Waqas-Hirose** [comment]
Fixed

**Comment by matsumoto777** [comment]
もう少し落ち着いてソースコードを書いてください。

1) インデントがずれている
2) '''labelSwitch.frame.size = switchSize'''は全くの無駄
3) ２つのブロックで異なるのは```CGRect(x: btnLogout.frame.minX...```の部分だけとの認識。
であれば、```let  btn = btnLogin.isHidden ? btnLogout : btnLogin```とする等、書き方をもう少し工夫できるのではないか？

```
        if(btnLogin.isHidden){
            let switchSize = labelSwitch.sizeThatFits(CGSize(width: frame.size.width, height: CGFloat.greatestFiniteMagnitude))
                   labelSwitch.frame.size = switchSize
                   self.labelSwitch.frame = CGRect(x: btnLogout.frame.minX-10-switchSize.width , y: buttonsYPosition, width: labelSwitch.bounds.width+5 , height: buttonHeight!)
        } else {
            let switchSize = labelSwitch.sizeThatFits(CGSize(width: frame.size.width, height: CGFloat.greatestFiniteMagnitude))
                   labelSwitch.frame.size = switchSize
                   self.labelSwitch.frame = CGRect(x: btnLogin.frame.minX-10-switchSize.width , y: buttonsYPosition, width: labelSwitch.bounds.width+5 , height: buttonHeight!)
        }
```

**Comment by Waqas-Hirose** [comment]
This was my mistake and sorry for this. I have moved out the common code from if else. 
Issue is fixed.
